#GATEWAY'S CONFIG
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./character/myh2database/myh2file
    password: sa
    username: mypass
    driverClassName: org.h2.Driver
    #data: classpath:./postdata.sql
    initialize: true
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

  application:
    name: characterservice
